### ISSUE TITLE
mastodon対応

### ISSUE THREAD

**Issue by mak0tia** [TinyKitten/KittenNowPlaying#2]
mastodonに投稿できるようにする

**Comment by TinyKitten** [comment]
Mastoshareでできそうだけどハッシュタグ勝手に消して #mastoshare 付けてくるしどうしようかな

**Comment by mak0tia** [comment]
API直接叩くのはダメなの?

**Comment by TinyKitten** [comment]
よくわかんないから調べてみる

**Comment by mak0tia** [comment]
ライブラリとか使わなくてもこんな感じでできるし即実装できる
https://qiita.com/jtodo/items/b97afc939d6a86d1cd14#%E6%9B%B8%E3%81%8D%E8%BE%BC%E3%81%BF

**Comment by TinyKitten** [comment]
これインスタンスに依存しない？

**Comment by mak0tia** [comment]
設定作っちゃえばよくね

**Comment by TinyKitten** [comment]
それもそうか

**Comment by TinyKitten** [comment]
#4 で対応
